[package]
name = "teo-language-parser"
description = "TEO language parser."
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["stdfs"]
stdfs = ["path-clean"]

[dependencies]
logos = "0.15.0"
path-clean = { version = "1.0.1", optional = true }
